POST http://localhost:8000/api/v2/listing/create-listing
Content-Type: application/json

{
  "category": "Warehouses",
  "description": "Hall",
  "discountPrice": "399983",
  "name": "Hall",
  "originalPrice": "3000",
  "propertyId": "67d95ce946b3c78fb8e19012",
  "stock": "1",
  "tags": []
}
